# Generated by Django 3.0.3 on 2020-02-13 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogpost',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('category', models.CharField(default='', max_length=50)),
                ('sub_category', models.CharField(default='', max_length=50)),
                ('desc', models.CharField(max_length=1000)),
                ('pub_date', models.DateField(auto_now_add=True)),
                ('thumbnail', models.ImageField(default='', upload_to='blog/post/images')),
            ],
        ),
    ]
